# ===============================================================
# GoReleaser config for Proxmox Backup Go
# Maintainer: tis24dev <github@tis24.it>
# GPG key ID: CD28A21CC11B270E
# ===============================================================

version: 2
project_name: proxmox-backup
dist: build

before:
  hooks:
    - go mod tidy

builds:
  - id: proxmox-backup
    main: ./build/proxmox-backup
    binary: proxmox-backup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}

checksum:
  name_template: "SHA256SUMS"

signs:
  - id: gpg-checksum-sign
    cmd: gpg
    artifacts: checksum
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--local-user=CD28A21CC11B270E"
      - "--detach-sign"
      - "--output"
      - "${signature}"
      - "${artifact}"

release:
  github:
    owner: tis24dev
    name: proxmox-backup
  draft: false
  prerelease: false
  name_template: "{{ .Tag }}"

changelog:
  use: git
  sort: asc
